[package]
edition = "2021"
name = "lldb-stub"
version = "0.1.0"

[dependencies]
lldb = {path = "../lldb"}
weaklink = {git = "https://github.com/vadimcn/weaklink.git"}

[build-dependencies]
toml = "0.8.21"
cc = "1.2.20"
weaklink_build = {git = "https://github.com/vadimcn/weaklink.git"}
